// export {ShipDetailPage} from './page/ship-detail.page';
// export {ShipSummaryComponent} from './component/ship-summary.component';
export { ShipSummary } from './data/ship-summary';
export { ShipInfoComponent } from './component/ship-info.component';
export { VesselGroupPage } from './page/vessel-group.page';
export { VesselGroupService } from './service/vessel-group.service';
export { ShipDynamicComponent } from './component/ship-dynamic.component';
export { ShipArchiveComponent } from './component/ship-archive.component';
export { NearbyShipComponent } from './component/nearby-ship.component';
export { ShipDetailPage } from './page/ship-detail.page';
export { ShipModule } from './ship.module';
export { VesselGroupMemberPage } from './page/vessel-group-member.page';