"use strict";
// export {ShipDetailPage} from './page/ship-detail.page';
// export {ShipSummaryComponent} from './component/ship-summary.component';
var ship_summary_1 = require('./data/ship-summary');
exports.ShipSummary = ship_summary_1.ShipSummary;
var ship_info_component_1 = require('./component/ship-info.component');
exports.ShipInfoComponent = ship_info_component_1.ShipInfoComponent;
var vessel_group_page_1 = require('./page/vessel-group.page');
exports.VesselGroupPage = vessel_group_page_1.VesselGroupPage;
var vessel_group_service_1 = require('./service/vessel-group.service');
exports.VesselGroupService = vessel_group_service_1.VesselGroupService;
